version: '3.9'

services:
  activemq:
    image: rmohr/activemq
    container_name: 'activemq'
    ports:
      - 61616:61616
    volumes:
      - ~/Documents/data/activemq/data:/data/activemq
      - ~/Documents/data/activemq/log:/var/log/activemq